# Generated by Django 3.1.2 on 2021-04-18 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
