# Generated by Django 3.1.2 on 2021-04-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_request',
            name='patient_image',
            field=models.ImageField(default='d.png', upload_to='uploded_image/'),
        ),
    ]
