# Generated by Django 3.1.7 on 2021-04-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pescription',
            name='suggestion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
