# Generated by Django 3.1.7 on 2021-04-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_pescription_suggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pescription',
            name='suggestion',
        ),
    ]
