# Generated by Django 3.1.7 on 2021-04-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_remove_pescription_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pescription',
            name='medical_suggestion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
