# Generated by Django 3.1.7 on 2021-04-22 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20210423_0532'),
        ('doctors', '0004_pescription_medical_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pescription',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.patient'),
        ),
    ]
