# Generated by Django 3.1.7 on 2021-03-23 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='phone',
        ),
    ]
