# Generated by Django 3.1.7 on 2021-04-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210410_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='degre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
