# Generated by Django 3.1.7 on 2021-04-09 22:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210410_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='uploded_image/'),
            preserve_default=False,
        ),
    ]
