# Generated by Django 3.1.7 on 2021-04-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210410_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Neurology', 'Neurology'), ('Dentist', 'Dentist'), ('Orthopedic', 'Orthopedic'), ('Urology', 'Urology')], max_length=200, null=True),
        ),
    ]
