# Generated by Django 3.1.7 on 2021-04-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210413_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(choices=[('Neurology', 'Neurology'), ('Dentist', 'Dentist'), ('Urology', 'Urology'), ('Orthopedic', 'Orthopedic'), ('Cardiologist', 'Cardiologist')], max_length=200, null=True),
        ),
    ]
