# Generated by Django 3.1.2 on 2021-04-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210413_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(choices=[('Neurology', 'Neurology'), ('Dentist', 'Dentist'), ('Cardiologist', 'Cardiologist'), ('Orthopedic', 'Orthopedic'), ('Urology', 'Urology')], max_length=200, null=True),
        ),
    ]
