# Generated by Django 3.1.2 on 2021-04-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210416_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Urology', 'Urology'), ('Dentist', 'Dentist'), ('Neurology', 'Neurology'), ('Orthopedic', 'Orthopedic')], max_length=200, null=True),
        ),
    ]
