# Generated by Django 3.1.2 on 2021-04-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20210417_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(choices=[('Dentist', 'Dentist'), ('Neurology', 'Neurology'), ('Urology', 'Urology'), ('Orthopedic', 'Orthopedic'), ('Cardiologist', 'Cardiologist')], max_length=200, null=True),
        ),
    ]
