# Generated by Django 3.1.2 on 2021-04-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210417_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(choices=[('Neurology', 'Neurology'), ('Orthopedic', 'Orthopedic'), ('Cardiologist', 'Cardiologist'), ('Dentist', 'Dentist'), ('Urology', 'Urology')], max_length=200, null=True),
        ),
    ]
