# Generated by Django 3.1.2 on 2021-04-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210417_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(choices=[('Dentist', 'Dentist'), ('Urology', 'Urology'), ('Orthopedic', 'Orthopedic'), ('Cardiologist', 'Cardiologist'), ('Neurology', 'Neurology')], max_length=200, null=True),
        ),
    ]
