# Generated by Django 3.1.2 on 2021-04-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20210417_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(choices=[('Orthopedic', 'Orthopedic'), ('Urology', 'Urology'), ('Dentist', 'Dentist'), ('Cardiologist', 'Cardiologist'), ('Neurology', 'Neurology')], max_length=200, null=True),
        ),
    ]
