# Generated by Django 3.1.2 on 2021-04-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20210418_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Orthopedic', 'Orthopedic'), ('Neurology', 'Neurology'), ('Urology', 'Urology'), ('Dentist', 'Dentist')], max_length=200, null=True),
        ),
    ]
