# Generated by Django 3.1.2 on 2021-04-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20210418_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(choices=[('Dentist', 'Dentist'), ('Cardiologist', 'Cardiologist'), ('Orthopedic', 'Orthopedic'), ('Neurology', 'Neurology'), ('Urology', 'Urology')], max_length=200, null=True),
        ),
    ]
