# Generated by Django 3.1.2 on 2021-04-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20210418_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(choices=[('Orthopedic', 'Orthopedic'), ('Neurology', 'Neurology'), ('Dentist', 'Dentist'), ('Urology', 'Urology'), ('Cardiologist', 'Cardiologist')], max_length=200, null=True),
        ),
    ]
