# Generated by Django 3.1.2 on 2021-04-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20210418_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(choices=[('Orthopedic', 'Orthopedic'), ('Neurology', 'Neurology'), ('Urology', 'Urology'), ('Cardiologist', 'Cardiologist'), ('Dentist', 'Dentist')], max_length=200, null=True),
        ),
    ]
