# Generated by Django 3.1.2 on 2021-04-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20210419_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dentist', 'Dentist'), ('Urology', 'Urology'), ('Orthopedic', 'Orthopedic'), ('Neurology', 'Neurology')], max_length=200, null=True),
        ),
    ]
