# Generated by Django 3.1.2 on 2021-04-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20210419_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(choices=[('Neurology', 'Neurology'), ('Urology', 'Urology'), ('Orthopedic', 'Orthopedic'), ('Cardiologist', 'Cardiologist'), ('Dentist', 'Dentist')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profile_pic',
            field=models.ImageField(default='d.png', upload_to='uploded_image/'),
        ),
    ]
