# Generated by Django 3.1.7 on 2021-04-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20210419_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(choices=[('Dentist', 'Dentist'), ('Orthopedic', 'Orthopedic'), ('Urology', 'Urology'), ('Cardiologist', 'Cardiologist'), ('Neurology', 'Neurology')], max_length=200, null=True),
        ),
    ]
