# Generated by Django 3.1.7 on 2021-04-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20210423_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(choices=[('Orthopedic', 'Orthopedic'), ('Dentist', 'Dentist'), ('Neurology', 'Neurology'), ('Urology', 'Urology'), ('Cardiologist', 'Cardiologist')], max_length=200, null=True),
        ),
    ]
