# Generated by Django 3.1.7 on 2021-04-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20210424_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(choices=[('Neurology', 'Neurology'), ('Cardiologist', 'Cardiologist'), ('Urology', 'Urology'), ('Orthopedic', 'Orthopedic'), ('Dentist', 'Dentist')], max_length=200, null=True),
        ),
    ]
